version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      VERSION: 1.19.2 #Specify MC Version
      FORGE_VERSION: 43.2.14 #Specify Forge Version
      DIFFICULTY: hard

    ports:
      - "25565:25565"
    volumes:
      - data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}