version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test      

  phpmyadmin:
    image: 'phpmyadmin:latest'
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
