version: "3.9"
services:
  whoami:
    image: "traefik/whoami"
    container_name: "traefik-whoami"
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoamitest.home.arpa`)
      - traefik.http.routers.whoami.entrypoints=web

networks:
  docker_services:
    external: true