version: '3'
services:

  mongo:
      image: mongo:latest
      container_name: mongo
      #entrypoint: ["mongod","--config","/etc/mongo/mongod.conf"]
      environment:
        MONGO_INITDB_DATABASE: mytestdb
        MONGO_INITDB_ROOT_PASSWORD: "myadminpass"
        MONGO_INITDB_ROOT_USERNAME: "myadmin"
        MONGODB_DB_PASSWORD: "mydevpass"
        MONGODB_DB_USERNAME: "mydevuser"
      ports:
        - "27017:27017"
      command:
        --port 27017
        --bind_ip 0.0.0.0
        --logappend
      volumes:
        #- "./docker/log/mongod:/var/log/mongodb"
        #- "./docker/data/mongod:/data/db"
        #- "./mongod.conf:/etc/mongo/mongod.conf"
        - "./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js"
      #logging: *default-logging
      #restart: always