FROM php:8.1-apache

RUN apt-get update && apt-get install -y \
    git \
    curl \
    libzip-dev \
    unzip


RUN docker-php-ext-install zip

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer self-update