services:
  postgres:
    image: postgres:latest
    networks:
      - mynet
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
      - PGDATA=/var/lib/postgresql/data
    ports:
      - 5432:5432
 
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5845:80"
    networks:
      - mynet
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@test.com
      - PGADMIN_DEFAULT_PASSWORD=password

volumes:
  postgres-data: 

networks:
  mynet:
    driver: bridge
