version: '3.7'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.4
    environment:
      - MARIADB_USER=bn_magento
      - MARIADB_DATABASE=bitnami_magento
      - MARIADB_ROOT_PASSWORD=my_cool_secret
      - MARIADB_PASSWORD=my_cool_secret
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  magento:
    image: docker.io/bitnami/magento:2.4.0
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MAGENTO_HOST=0.0.0.0
      - MAGENTO_DATABASE_HOST=mariadb
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=bn_magento
      - MAGENTO_DATABASE_NAME=bitnami_magento
      - MAGENTO_PASSWORD=my_cool_secret
      - MAGENTO_DATABASE_PASSWORD=my_cool_secret
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9201

    volumes:
      - 'magento_data:/bitnami/magento'
    depends_on:
      - mariadb
      - elasticsearch
  elasticsearch:
    image: docker.io/bitnami/elasticsearch:7
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
volumes:
  mariadb_data:
    driver: local
  magento_data:
    driver: local
  elasticsearch_data:
    driver: local